version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing SonarQube Scanner...
      - curl -o sonar-scanner-cli.zip -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
      - unzip sonar-scanner-cli.zip -d /opt
      - export PATH=$PATH:/opt/sonar-scanner-4.6.2.2472-linux/bin
  build:
    commands:
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=demo \
        -Dsonar.host.url=http://13.201.53.198:9000 \
        -Dsonar.login=squ_2f217b09857d7c2af399d2b22f807de615667451
